# .github/workflows/secret-scanner.yml

name: Secret Scanner 🛡️

# This workflow runs on every push to any branch and on every pull request.
on: [push, pull_request]

jobs:
  scan_secrets:
    # Use the latest version of Ubuntu for our runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code so we can scan it.
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install git-secrets from the source. This is the most reliable method on a fresh runner.
      - name: Install git-secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          sudo make install
          cd ..
          rm -rf git-secrets

      # Step 3: Configure git-secrets for the repository.
      - name: Configure git-secrets
        run: |
          # Initialize git-secrets in the repository context.
          git secrets --install
          # Add the default AWS patterns to scan for.
          git secrets --register-aws
          # You can also add your own custom patterns.
          # For example, let's add a rule to find anything defined as "PASSWORD".
          git secrets --add '.*PASSWORD.*'

      # Step 4: Run the scan. The -r flag makes it recursive.
      # If a secret is found, this step will exit with a non-zero status code, causing the job to fail.
      - name: Scan for secrets
        run: git secrets --scan -r .